# Generated by Django 6.1.1 on 2026-09-18 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobMatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_username', models.CharField(max_length=255)),
                ('job_description_hash', models.CharField(db_index=True, max_length=64)),
                ('job_description_text', models.TextField()),
                ('match_result_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['target_username', 'job_description_hash'], name='jobs_jobmat_target__1dec7d_idx')],
            },
        ),
    ]
