# Generated by Django 6.0.7 on 2026-08-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("developers", "0002_profile_tech_stack"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="ai_summary",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="account_age",
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="username",
            field=models.CharField(max_length=255),
        ),
    ]
