# Generated by Django 6.0.7 on 2026-08-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("developers", "0003_profile_ai_summary_alter_profile_account_age_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="job_match",
            field=models.TextField(blank=True),
        ),
    ]
